# -*- coding: utf-8 -*-
"""
Build demonstration video loops for the synthetic texture experiments.

Two mirrored scenarios, each generated by alpha-blending one texture into the
other (see toskipornot/data/generate-textures-*-variation.py):

    background   foreground texture bleeds into the background
                 blend(bg, fg, alpha) composited outside the mask
    foreground   background texture bleeds into the foreground
                 blend(fg, bg, alpha) composited inside the mask

In both, alpha -> 1 collapses the texture disparity between object and
background, so the segmentation task degrades from trivial to impossible. Every
model here was trained at alpha = 0.10 (maximum disparity), and the time axis
sweeps the test alpha across all 15 available levels and back, so the clip loops.

Layout matches make_robustness_video: 4 columns x 6 rows (one per architecture).

Usage:
    python -m toskipornot.visualization.make_synthetic_video --scenario both
"""

import argparse
import os
import sys
from glob import glob

import numpy as np
import torch
from monai.networks.layers import Norm
from monai.networks.nets import AttentionUnet, BasicUNetPlusPlus, UNet, VNet

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))

from toskipornot.config import (  # noqa: E402
    checkpoint_path,
    data_path,
    describe,
    require,
    results_path,
)
from toskipornot.models.NoSkipUnet import NoSkipUNet  # noqa: E402
from toskipornot.models.NoSkipVnet import NoSkipVNet  # noqa: E402
from toskipornot.visualization.make_robustness_video import (  # noqa: E402
    MODELS,
    dice,
    draw_grid,
    encode,
    predict,
    read_gray,
    scale_intensity,
)

# Every alpha level present in data/{background,foreground}-processed.
ALPHAS = [10, 20, 30, 40, 50, 60, 70, 80, 82, 85, 88, 90, 92, 95, 98]
TRAIN_ALPHA = 10  # the in-domain condition all these checkpoints were trained at

# Ping-pong so the clip loops without a jump.
SWEEP = ALPHAS + ALPHAS[-2:0:-1]

# Models trained on the first 80 images; only 80: is test data.
TEST_START = 80

# Locations come from toskipornot.config; see .env.example.
SCENARIOS = {
    "background": {
        "title": "Synthetic — foreground texture bleeding into the background",
        "data": data_path("background-processed"),
        "models": checkpoint_path("synthetic-background"),
    },
    "foreground": {
        "title": "Synthetic — background texture bleeding into the foreground",
        "data": data_path("foreground-processed"),
        "models": checkpoint_path("synthetic-foreground"),
    },
}

# Directory naming in the synthetic runs differs from the medical ones.
RUN_NAME = {
    "UNet": "unet",
    "AttentionUNet": "AttentionUNet",
    "UNet++": "UNet++",
    "NoSkipUNet": "NoSkipUNet",
    "VNet": "vnet",
    "NoSkipVNet": "NoSkipVNet",
}

# From toskipornot/visualization/test-synthetic-robustness.py: the synthetic runs
# use a 5-level encoder, shallower than the 256px medical runs.
SYNTH_PARAMS = {
    "UNet": dict(
        spatial_dims=2,
        in_channels=1,
        out_channels=1,
        channels=(16, 32, 64, 128, 256),
        strides=(2, 2, 2, 2),
        num_res_units=0,
        norm=Norm.BATCH,
        act="ReLU",
    ),
    "AttentionUNet": dict(
        spatial_dims=2,
        in_channels=1,
        out_channels=1,
        channels=(16, 32, 64, 128, 256),
        strides=(2, 2, 2, 2),
    ),
    "UNet++": dict(
        spatial_dims=2,
        in_channels=1,
        out_channels=1,
        features=(16, 32, 64, 128, 256, 512),
        norm=Norm.BATCH,
        act="ReLU",
        bias=False,
    ),
    "VNet": dict(
        spatial_dims=2,
        in_channels=1,
        out_channels=1,
        act="ReLU",
        dropout_prob_down=0.0,
        dropout_prob_up=(0.0, 0.0),
    ),
    "NoSkipVNet": dict(
        spatial_dims=2, in_channels=1, out_channels=1, act="ReLU", dropout_prob=0.0
    ),
}
SYNTH_PARAMS["NoSkipUNet"] = SYNTH_PARAMS["UNet"]

BUILDERS = {
    "UNet": UNet,
    "AttentionUNet": AttentionUnet,
    "UNet++": BasicUNetPlusPlus,
    "NoSkipUNet": NoSkipUNet,
    "VNet": VNet,
    "NoSkipVNet": NoSkipVNet,
}


def alpha_dir(root, alpha):
    return os.path.join(root, f"alphablend_0p{alpha}_normal")


def load_models(models_root):
    loaded = {}
    for name in MODELS:
        run = f"{RUN_NAME[name]}_dice_alphablend_0p{TRAIN_ALPHA:02d}_normal_seed_1"
        ckpt = os.path.join(
            models_root, run, "best_metric_model_segmentation2d_dict.pth"
        )
        if not os.path.isfile(ckpt):
            raise FileNotFoundError(ckpt)
        model = BUILDERS[name](**SYNTH_PARAMS[name])
        model.load_state_dict(torch.load(ckpt, map_location="cpu"))
        model.eval()
        loaded[name] = {"model": model, "seed": 1}
        print(f"    loaded {name:14s} from {run}")
    return loaded


def load_case(data_root, alpha, idx):
    images = sorted(glob(os.path.join(alpha_dir(data_root, alpha), "train", "*.png")))
    masks = sorted(glob(os.path.join(alpha_dir(data_root, alpha), "mask", "*.png")))
    return scale_intensity(read_gray(images[idx])), (
        read_gray(masks[idx]) > 127
    ).astype(np.float32)


def pick_images(data_root, n_images):
    """Evenly spaced cases from the held-out tail of the set."""
    masks = sorted(glob(os.path.join(alpha_dir(data_root, TRAIN_ALPHA), "mask", "*.png")))
    pool = list(range(TEST_START, len(masks)))
    step = max(1, len(pool) // n_images)
    return [pool[i * step] for i in range(n_images)]


def build(scenario, args):
    cfg = SCENARIOS[scenario]
    print(f"\n=== synthetic/{scenario}: {cfg['title']}")
    require(cfg["data"])
    require(cfg["models"])
    device = torch.device(args.device)
    models = load_models(cfg["models"])

    image_ids = pick_images(cfg["data"], args.n_images)
    print(f"    test cases: {image_ids}  (held out; trained on 0..{TEST_START - 1})")

    preds, scores, images, gts = {}, {}, {}, {}
    total = len(image_ids) * len(ALPHAS) * len(MODELS)
    step = 0
    for idx in image_ids:
        for alpha in ALPHAS:
            image, gt = load_case(cfg["data"], alpha, idx)
            images[(idx, alpha)] = image
            gts[idx] = gt
            for name in MODELS:
                pred = predict(models[name]["model"], image, device)
                preds[(idx, alpha, name)] = pred
                scores[(idx, alpha, name)] = dice(pred, gt)
                step += 1
                if step % 60 == 0 or step == total:
                    print(f"    inference {step}/{total}")

    frame_dir = os.path.join(args.out_dir, f"frames_synthetic_{scenario}")
    os.makedirs(frame_dir, exist_ok=True)
    for old in glob(os.path.join(frame_dir, "*.png")):
        os.remove(old)

    n = 0
    for idx in image_ids:
        for alpha in SWEEP:
            subtitle = (
                f"blend $\\alpha$={alpha / 100:.2f}"
                + ("  (in-domain, as trained)" if alpha == TRAIN_ALPHA else "")
                + f"     ·     test case {idx}"
            )
            draw_grid(
                clean=images[(idx, TRAIN_ALPHA)],
                gt=gts[idx],
                perturbed=images[(idx, alpha)],
                preds={m: preds[(idx, alpha, m)] for m in MODELS},
                dices={m: scores[(idx, alpha, m)] for m in MODELS},
                seeds={m: 1 for m in MODELS},
                title=cfg["title"],
                subtitle=subtitle,
                out_path=os.path.join(frame_dir, f"frame_{n:04d}.png"),
            )
            n += 1
    print(f"    rendered {n} frames")

    os.makedirs(args.out_dir, exist_ok=True)
    out_file = os.path.join(args.out_dir, f"robustness_synthetic_{scenario}.mp4")
    encode(frame_dir, out_file, args.seconds_per_frame, crf=args.crf)
    print(
        f"    wrote {out_file}  ({os.path.getsize(out_file) / 1e6:.1f} MB, "
        f"{n * args.seconds_per_frame:.0f}s)"
    )

    print("    Dice, mean over test cases:")
    for name in MODELS:
        row = [np.mean([scores[(i, a, name)] for i in image_ids]) for a in ALPHAS]
        print(f"      {name:14s} " + " ".join(f"{v:>5.3f}" for v in row))
    print(f"      {'':14s} " + " ".join(f"{a / 100:>5.2f}" for a in ALPHAS))
    return out_file


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--scenario", default="both", choices=list(SCENARIOS) + ["both"])
    ap.add_argument("--n-images", type=int, default=3)
    ap.add_argument("--seconds-per-frame", type=float, default=0.42)
    ap.add_argument("--out-dir", default=str(results_path("videos")))
    ap.add_argument("--crf", type=int, default=20, help="x264 quality; higher = smaller file")
    ap.add_argument(
        "--show-config",
        action="store_true",
        help="print the resolved data/checkpoint/results locations and exit",
    )
    ap.add_argument("--device", default="cpu")
    args = ap.parse_args()

    if args.show_config:
        print(describe())
        return

    targets = list(SCENARIOS) if args.scenario == "both" else [args.scenario]
    made = [build(s, args) for s in targets]
    print("\nDone:")
    for m in made:
        print("  " + m)


if __name__ == "__main__":
    main()
